### ISSUE TITLE
Doesn't work on Blender 3.0

### ISSUE THREAD

**Issue by SrFidelis** [julienduroure/ExtraGroups#3]
Impossible to use in blender 3.0, it just doesn't install.

**Comment by julienduroure** [comment]
I can't reproduce.
Can you please copy/paste your console log.
What version are you using?
You should have at least 1.1.0 (and better 1.1.1 in this repository)

**Comment by SrFidelis** [comment]
1. Install 
![install-1](https://user-images.githubusercontent.com/61887607/131253888-3a17fd27-f195-4dc6-b2d4-918902d1dc24.png)

**2. Where is?** 
![install-3_whereis](https://user-images.githubusercontent.com/61887607/131253910-bb487802-3f45-4af1-b7cf-ccaabccdfdbe.png)

**Comment by julienduroure** [comment]
ExtraGroups is an animation/rigging addon.
Corresponding tab is visible when an armature is selected, in pose mode.
